### ISSUE TITLE
关于ioctree和ikdtree的比较

### ISSUE THREAD

**Issue by minghongss** [zhujun3753/i-octree#5]
您好，感谢您的工作！
我看了论文，在论文中只对比了ikdtree，但其实除了ikdtree外，还有个高博的ivox为代表的faster_lio，不知道您私下是否对比过ioctree和ivox，这二者在实时性与精度上对比效果如何？

**Comment by zhujun3753** [comment]
![image](https://github.com/zhujun3753/i-octree/assets/56210041/1757c65a-2ee4-478f-a335-0a1ee00b6b70)
您好，感谢您关注我们的工作！
我们也注意到了高博的ivox，不过ivox其实并不是严格tree结构，更像是对空间的网格划分，ivox在进行knn搜索的时候只能局限于给定的区域，搜索的结果并不完整，因此我们并没有和其对比。

**Comment by minghongss** [comment]
感谢您的回复，我最近正在测试您的i-octree，请问有没有什么参数可以进行微调呢？或者有没有提供调参手册。
测试结果：
ikdtree体素大小为0.5，不触发删除，耗时为3.297860ms
ioctree默认参数，不触发删除，耗时为2.875930ms。
基于fastlio测试。貌似也没有快很多？

**Comment by Darling169** [comment]
@minghongss 您好，请问您开源ioctree应用在fast_lio2的代码吗？
