### ISSUE TITLE
关于八叉树深度的疑惑

### ISSUE THREAD

**Issue by minghongss** [zhujun3753/i-octree#6]
您好，感谢您和您团队的工作！
我看了论文和源码，我发现，在每次新加入点时，都会判断是否存在存在点位于当前树的外面，如果在当前树的外面，就会在当前树的基础上，将Extent扩大二倍，新建一个树，把当前树接在新建树的后面；而八叉树由于它的特性原因，每一层只有八个子节点，那么这样子的话，随着时间运行，这个八叉树的深度就会越来越深，这样可能就会导致在近邻搜索的时候，递归层数很深，从而降低搜索效率呢？
下面两个图分别为代码和论文对应扩大八叉树的地方：
![image](https://github.com/zhujun3753/i-octree/assets/76800494/db909100-b65d-478b-af93-4ec82e3234e5)
![image](https://github.com/zhujun3753/i-octree/assets/76800494/b5814637-e11b-4b03-bcaa-57887d23189c)

**Comment by zhujun3753** [comment]
感谢您关注我们的工作！！
深度不会越来越深的，除非场景范围不断扩张。
