### ISSUE TITLE
疑似bug

### ISSUE THREAD

**Issue by minghongss** [zhujun3753/i-octree#7]
如果当我只使用一个点初始化octree的时候
![image](https://github.com/zhujun3753/i-octree/assets/76800494/d6e06758-0926-4689-8d96-530632344468)
max=min，此时的创建的octant的extent=0，如果后面我在对这个octree更新的时候，
![image](https://github.com/zhujun3753/i-octree/assets/76800494/d9970c5f-e259-484c-ba29-7fc8eac5529d)
这里就会陷入死循环，因为extent一直都是0

这里还有个问题，希望可以解答一下[#5](https://github.com/zhujun3753/i-octree/issues/5)

**Comment by zhujun3753** [comment]
感谢您关注我们的工作，感谢您指出bug，非常感谢！！！
